baseURL = 'https://bemoty.dev/'
locale = 'en-us'
title = "bemoty | Joshua Winkler"
enableRobotsTXT = true

[taxonomies]
tag = "tags"

[params]
author = "Joshua Winkler"
description = "I am a software engineer based in Innsbruck, Austria."

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"
